default:
  image: golang:1.25-bullseye
  tags:
    - pangea-internal

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - lint
  - unit_tests
  - integration_tests
  - publish

include:
  - /pangea-sdk/.sdk-ci.yml
