default:
  image: golang:1.23-bullseye@sha256:3b0ff3ec7b3dc2e8d48ab22f2dcca763251ea9d9b01572878543513c31b8fbcb
  tags:
    - pangea-internal

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - lint
  - unit_tests
  - integration_tests
  - examples
  - publish

include:
  - /examples/.examples-ci.yml
  - /pangea-sdk/.sdk-ci.yml
