default:
  image: golang:1.23-bullseye@sha256:00e4a935148b7caae84a230d886c9375820b5c048310c368ecb6824c936a4a52
  tags:
    - pangea-internal

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - lint
  - unit_tests
  - integration_tests
  - examples
  - publish

include:
  - /examples/.examples-ci.yml
  - /pangea-sdk/.sdk-ci.yml
