.go-sdk-base:
  before_script:
    - cd packages/pangea-sdk
    - go install github.com/boumenot/gocover-cobertura@latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

lint:
  extends: .go-sdk-base
  stage: lint
  script:
    - make verify

generate_docs:
  extends: .go-sdk-base
  stage: lint
  allow_failure: true
  script:
    - make docgen
  artifacts:
    expire_in: 1 month
    expose_as: go_sdk
    paths: ['go_sdk.json']
    when: on_success

testing:
  extends: .go-sdk-base
  stage: unit_tests
  script:
    - make unit

integration:
  extends: .go-sdk-base
  stage: integration_tests
  script:
    - make integration
