.go-sdk-base:
  before_script:
    - cd pangea-sdk/v3
    - go install github.com/boumenot/gocover-cobertura@latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.go-sdk-test-base:
  variables:
  # Set each service test environment
    SERVICE_AUDIT_ENV: LVE
    SERVICE_AUTHN_ENV: LVE
    SERVICE_EMBARGO_ENV: LVE
    SERVICE_FILE_SCAN_ENV: LVE
    SERVICE_IP_INTEL_ENV: LVE
    SERVICE_DOMAIN_INTEL_ENV: LVE
    SERVICE_URL_INTEL_ENV: LVE
    SERVICE_FILE_INTEL_ENV: LVE
    SERVICE_USER_INTEL_ENV: LVE
    SERVICE_REDACT_ENV: LVE
    SERVICE_VAULT_ENV: LVE

  before_script:
    - echo $ENV
    - echo $CLOUD
  # Update environment variables
  # Domain
    - export PANGEA_INTEGRATION_DOMAIN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_DOMAIN_${ENV}_${CLOUD})"
  # Tokens
    - export PANGEA_INTEGRATION_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}_${CLOUD})"
  # Config IDs
    - export PANGEA_AUDIT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_2_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_2_${ENV}_${CLOUD})"

    - cd pangea-sdk/v3
    - go install github.com/boumenot/gocover-cobertura@latest

  parallel:
    matrix:
      - CLOUD: [AWS, GCP]

  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

go-sdk-lint:
  extends: .go-sdk-base
  stage: lint
  script:
    - make verify

go-sdk-generate-docs:
  extends: .go-sdk-base
  stage: lint
  allow_failure: true
  script:
    - make docgen
  artifacts:
    expire_in: 1 month
    expose_as: go_sdk
    paths: ['pangea-sdk/go_sdk.json']
    when: on_success

go-sdk-unit-testing:
  extends: .go-sdk-base
  stage: unit_tests
  script:
    - make unit

go-sdk-it-audit:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_AUDIT_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/audit/...

go-sdk-it-authn:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_AUTHN_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/authn/...

go-sdk-it-domain-intel:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_DOMAIN_INTEL_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/domain_intel/...

go-sdk-it-embargo:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_EMBARGO_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/embargo/...

go-sdk-it-file-intel:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_FILE_INTEL_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/file_intel/...

go-sdk-it-file-scan:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_FILE_SCAN_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/file_scan/...
  rules:
    - if: '$CLOUD == "GCP"'
      allow_failure: true
    - if: '$CLOUD != "GCP"'
      allow_failure: false

go-sdk-it-ip-intel:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_IP_INTEL_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/ip_intel/...

go-sdk-it-redact:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_REDACT_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/redact/...

go-sdk-it-url-intel:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_URL_INTEL_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/url_intel/...

go-sdk-it-user-intel:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_USER_INTEL_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/user_intel/...

go-sdk-it-vault:
  extends: .go-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_VAULT_ENV}
  script:
    - go test -count=1 -tags integration -v ./service/vault/...

.go-sdk-staging-tests:
  extends: .go-sdk-test-base
  variables:
    ENV: STG
    SERVICE_AUDIT_ENV: STG
    SERVICE_AUTHN_ENV: STG
    SERVICE_EMBARGO_ENV: STG
    SERVICE_FILE_SCAN_ENV: STG
    SERVICE_IP_INTEL_ENV: STG
    SERVICE_DOMAIN_INTEL_ENV: STG
    SERVICE_URL_INTEL_ENV: STG
    SERVICE_FILE_INTEL_ENV: STG
    SERVICE_USER_INTEL_ENV: STG
    SERVICE_REDACT_ENV: STG
    SERVICE_VAULT_ENV: STG
  script:
    - make integration
